#!/bin/sh

case "$1" in
"C-x")      xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard ;;
"C-c")      while read file; do xclip -selection clipboard -target image/png "$file"; done ;;
"C-g")      tr '\n' '\0' | xargs -0 gimp & ;;
"C-period") while read file; do convert "$file" -rotate -270 "$file"; done ;;
"C-comma")  while read file; do convert "$file" -rotate -90 "$file"; done ;;
"C-minus")  while read file; do convert "$file" -rotate -180 "$file"; done ;;
"C-w")      while read file; do setroot -z "$file"; done ;;
"C-f")      tr '\n' '\0' | xargs -0 st -e vifmrun --select & ;;
esac

