use_nerdfont = true

[keybindings]
"e" = "queue"
"Space" = "playpause"
"y" = "share selected"
"Shift+y" = "share current"
"g" = "move top"
"Shift+g" = "move bottom"
"x" = "delete"
"d" = "move down 5"
"u" = "move up 5"
"Ctrl+d" = "move down 5"
"Ctrl+u" = "move up 5"
"Ctrl+f" = "move down 20"
"Ctrl+b" = "move up 20"

[theme]
background = "black"
primary = "light white"
secondary = "light black"
title = "green"
playing = "green"
playing_bg = "black"
highlight = "light white"
highlight_bg = "#484848"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "green"
statusbar_bg = "green"
cmdline = "light white"
cmdline_bg = "black"
